stages:
  prepare:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - data/raw/telco_churn.csv
      - params.yaml
    outs:
      - data/processed/telco_churn_clean.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/telco_churn_clean.csv
      - params.yaml
    outs:
      - models/model.pkl
    metrics:
      - metrics.json

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
      - data/processed/telco_churn_clean.csv
      - params.yaml
    outs:
      - reports/roc_curve.png
      - reports/confusion_matrix.png
      - reports/classification_report.txt
      - reports/evaluation_summary.json