stages:
  prepare:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - data/raw/telco_churn.csv
      - params.yaml
    outs:
      - data/processed/telco_churn_clean.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/telco_churn_clean.csv
      - params.yaml
    outs:
      - models/model.pkl
    metrics:
      - metrics.json
