data:
  raw_path: "data/raw/telco_churn.csv"
  processed_path: "data/processed/telco_churn_clean.csv"

model:
  C: 0.1
  max_iter: 1000
  class_weight: "balanced"

split:
  test_size: 0.3
  random_state: 42
  